# Generated by Django 3.2.9 on 2022-01-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_auto_20210727_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cet_percentile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cet_scorecard',
        ),
        migrations.RemoveField(
            model_name='application',
            name='jee_percentile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='jee_scorecard',
        ),
    ]
