# Generated by Django 3.2.9 on 2022-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_auto_20220107_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Bachelor of Business Information Systems', 'Bachelor of Business Information Systems'), ('Bachelor of Business Adminstration', 'Bachelor of Business Adminstration')], max_length=100),
        ),
    ]
