# Generated by Django 3.2.9 on 2022-01-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_alter_application_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='hsc_leaving_certificate',
            new_name='SLC_leaving_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_marksheet',
            new_name='SLC_marksheet',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_passing_certificate',
            new_name='SLC_passing_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_percentage',
            new_name='SLC_percentage',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_leaving_certificate',
            new_name='high_leaving_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_marksheet',
            new_name='high_marksheet',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_passing_certificate',
            new_name='high_passing_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_percentage',
            new_name='high_percentage',
        ),
    ]
