# Generated by Django 3.2.9 on 2022-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0027_auto_20220107_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student_profile',
        ),
        migrations.AddField(
            model_name='application',
            name='voucher',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
